version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ug_gym_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ug_gym_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gympassword123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ug_gym_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - gym_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ug_gym_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ugym.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gym_network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

networks:
  gym_network:
    driver: bridge
